### ISSUE TITLE
公開設定・自己紹介・mokuアイテムを調整してカレンダーを上部へ

### ISSUE THREAD

**Issue by TaroKuma3** [TaroKuma3/moku#14]
- [x] **公開設定**

→お名前の横にアイコン置くとスッキリ

- [x] **自己紹介とmokuアイテム**

→他の人に見せる部分で自分は見えなくていいのでカードをなくす

- [x] **カレンダーを上方へ**

→自分の直近mokuなど追加しようと思っているものとのバランスに注意

🔸pick upやMJNの位置も調整

**Comment by TaroKuma3** [comment]
関連： #23 
サインアップ後に使用方法を見せるにあたり画像を使う。
その時画像を使用したいので、これを先に対応する。

**Comment by TaroKuma3** [comment]
公開設定アイコン化OK
自己紹介とmokuアイテムカード削除OK
カレンダー上方へ移動OK

**Comment by dateofrock** [comment]
@TaroKuma3 カレンダーが上に上がって実に良い感じです！👍
