### ISSUE TITLE
Flashが消えると画面が全体的に上がるのがつらい

### ISSUE THREAD

**Issue by dateofrock** [TaroKuma3/moku#21]
ヘッダメニューの下にFlashメッセージが出るが、これが数秒で自動で消える時に、その分画面全体が上にせり上がる。

なにか記入したり、ボタンを押そうと思った瞬間に画面がせり上がると使いにくいです。

自動フェードアウトはやめたほうがいいような気がします。それか、消すならレイアウトは動かないほうが使いやすいです。

**Comment by TaroKuma3** [comment]
Duplicate of #3 
issueありがとうございます！
自分も気になっていてすでにissueに置いてました。
まとめかたがすぐにわからなかったので、ちょっと失礼な感じがしますが
こちらをクローズして#3にむりやりくっつけます。

**Comment by dateofrock** [comment]
@TaroKuma3 Issueが重複する場合は、どちらかのIssueに寄せてクローズするのが良いです。その際、duplicateというラベルをつけておけば、重複したんだな、ということがわかるのでなおGoodです！
