### ISSUE TITLE
moku一覧で成果物の数の表示が欲しい

### ISSUE THREAD

**Issue by dateofrock** [TaroKuma3/moku#22]
一覧画面ではこのように見えるが、成果物が登録されているかどうかの判別がつかない。
<img width="977" alt="スクリーンショット 2019-05-10 22 28 34" src="https://user-images.githubusercontent.com/313265/57530795-faa39000-7372-11e9-8fc0-07158c76c614.png">
成果物登録ボタンの近くにでも、登録数が表示されていると良いなと思います。

**Comment by TaroKuma3** [comment]
・成果物の数表示
・「成果物登録」を「成果物」にして、テーブル内は件数表示と登録ボタンを並べてみるか。

**Comment by TaroKuma3** [comment]
とりあえずそれらしく
ただちょっと違和感を感じる

リンクはとりあえず貼らず

**Comment by TaroKuma3** [comment]
cssでちょっと調整
リンクはやっぱり貼りたい気もするけれど悩ましいので
一旦これで完了にする
後日どうしても気になれば再考する
