### ISSUE TITLE
成果物が登録されていない時のmoku削除時のメッセージ

### ISSUE THREAD

**Issue by dateofrock** [TaroKuma3/moku#28]
成果物がない時は、この警告自体がいらないように思います。

![スクリーンショット 2019-05-15 0 14 21](https://user-images.githubusercontent.com/313265/57709870-c7c90700-76a6-11e9-9956-bfcd51a922e8.png)

**Comment by TaroKuma3** [comment]
ありがとうございます！
確かに成果物がないならいらなそう＋すぐ対処できる内容だったので
対応してみました。
