### ISSUE TITLE
MJNの初回表示が遅れて出てくる

### ISSUE THREAD

**Issue by dateofrock** [TaroKuma3/moku#30]
最初から出ているといいな・・・。

![スクリーンショット 2019-05-25 22 53 17](https://user-images.githubusercontent.com/313265/58370329-0b8dfd00-7f40-11e9-9c44-f145dc40827e.png)

**Comment by TaroKuma3** [comment]
ありがとうございます。同感です。
あれ、初回は0、以降5000でデータ拾いに行ってくれればいいんだと思ってるんですが、実際どう書く？という所が後回し中でした。
調べます。

**Comment by TaroKuma3** [comment]
moku開始後のmoku Timeも同様、最初の1000msになるまではただのブランクなので
直したい

**Comment by TaroKuma3** [comment]
- JSを動かせば、どうしても0,1,2,3…(ms)と動作までのブランクが生じてチラッとする。

- MJNについては`<ul id="justNowUl">  **ココ** </ul>`に、普通にデーター拾った変数挟んであげればできそうとヒントもらった。

**Comment by TaroKuma3** [comment]
- **moku開始後の画面も対応。**
**MJN**
mokus_controllerで同様にデーター拾ってeachで回した。

**ストップウォッチ**
`<h3 class="card-text text-center" id="timer">00:00:00</h3>`
このように00:00:00をベタ打ちで加筆しただけ。
