### ISSUE TITLE
アコーディオン

### ISSUE THREAD

**Issue by TaroKuma3** [TaroKuma3/moku#33]
なし（menu)

**Comment by TaroKuma3** [comment]
何かがかぶさっているのか、アコーディオンに使用しているcardの下線が消える。
さらに`aria-expanded="false"` `class="collapse`しているからmokuるまでのタップ数が増える。
trueにすれば見えている状態にできる。
↓
するとpicu upだけがアコーディオンとなり、違和感を感じる。

そもそもMJNのアコーディオン化ができていない（idの使い分けがわからなかった）時点で違和感。
picu upとMJNは同じ色・同じ種類のカードとして作っているから、片方だけアコーディオン、もう片方はただのカードではおかしい。

★アコーディオンを全て撤廃する

**Comment by TaroKuma3** [comment]
- スマホではサイズを小さく。
アイコンが５つ（管理者は７つ）あり、１個ずつ変更するのは面倒だったのでcssで１発で変えられるように修正。

- bootstrapのmarginのサイズは何pxか
pxじゃなくてremだったけれど以下が参考になった。
尚、以下ではm-ms-1などサイズによりmarginを書き分けることができるとあったが、
私の場合md以上はcard、md未満はaccordionと分ける必要があったので、それは使わなかった。
[https://webnetamemo.com/coding/bootstrap4/201710065870#margin](url)

**Comment by TaroKuma3** [comment]
実際にmokuに使っているBootstrapの「Accordion example」に書かれているサンプルコードいじった結果、2つ以上の折りたたみグループを繋げないために下線が消えていることが判明。

` data-parent="#accordionExample"` の一文で何枚ものカードをひとかたまりにするコードのようで、試しに `data-parent="#accordionExample"` を消してみたけれど（id定義の部分も）だめだった。

１枚のカードだけをアコーディオンさせるのには向いていないコードだったようだ。

**Comment by TaroKuma3** [comment]
完了

普通に「Example

**Comment by dateofrock** [comment]
すばらしい！ 👍
