### ISSUE TITLE
公開、非公開の表示をわかりやすくしてほしい

### ISSUE THREAD

**Issue by dateofrock** [TaroKuma3/moku#40]
#2 に関連するかもしれませんが、公開、非公開で「色を変える」などして、ぱっと見わかりやすい表示にしてほしいです。
![スクリーンショット 2019-06-09 20 52 33](https://user-images.githubusercontent.com/313265/59158691-d3b6b600-8af8-11e9-92ee-5b8483530c82.png)

**Comment by TaroKuma3** [comment]
ありがとうございます！確かにその方がわかりやすいですね。
ひとまずworks/showを修正しました。

他にも交換・非公開あったように思うので確認して適用します。

**Comment by TaroKuma3** [comment]
追加したelseにもid付与しないとcardの高さが崩れてる
